# Generated by Django 5.1.15 on 2026-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='show_in_notification',
            field=models.BooleanField(default=False, help_text="Include this field's value in the push-notification body. When no attribute is selected the body stays generic."),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='notify_title',
            field=models.CharField(blank=True, default='', help_text="Custom push-notification title. Blank falls back to 'New submission · <endpoint name>'.", max_length=100),
        ),
    ]
