# Generated by Django 5.1.15 on 2026-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_attribute_show_in_notification_endpoint_notify_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='show_as_data_header',
            field=models.BooleanField(default=False, help_text="For an `image` attribute: show it as the submission's header image throughout the app (detail banner, list thumbnails)."),
        ),
        migrations.AddField(
            model_name='attribute',
            name='show_as_subtitle',
            field=models.BooleanField(default=False, help_text="Use this field's value as the notification subtitle. At most one attribute per endpoint may be the subtitle — setting it here clears the flag on the endpoint's other attributes."),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='notify_logo',
            field=models.ImageField(blank=True, help_text="Optional logo shown as the notification's large icon. Uploaded via POST /api/endpoints/{id}/logo/.", null=True, upload_to='endpoint-logos/'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='show_in_notification',
            field=models.BooleanField(default=False, help_text="Include this field's value in the push-notification body. When no attribute is selected the body stays generic. For an `image` attribute this instead supplies the notification's picture."),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('phone', 'Phone'), ('date', 'Date'), ('boolean', 'Boolean'), ('image', 'Image URL')], default='text', max_length=16),
        ),
    ]
